version: 1.0.0-alpha{build}
image: Visual Studio 2017
branches:
  only:
  - master
skip_commits:
  files:
    - '**/*.txt'
    - '**/*.md'
environment:
  nugetOrgApiKey:
    secure: RoB7VF83e2Nk4/rIUilssnSNHmThFSHyEFeOtFBPKhOZQYwu8XvuqXS4seBEl+yG
  sonarLogin:
    secure: us3NmhirEyZlRItv0KXrdOeGZATXPrLl2r7b0qJp77NBsmQNo2iwLFt4zzXIJGRk
configuration: Release
dotnet_csproj:
  patch: false
init:
- ps: >- 
    git config --global --unset core.autocrlf;
    $env:isPrerelease = $env:APPVEYOR_BUILD_VERSION.Contains('-');
    if ($env:APPVEYOR_REPO_TAG -eq "true") {
        $env:packageVersion = $env:APPVEYOR_REPO_TAG_NAME;
        $env:dllVersion = $env:APPVEYOR_REPO_TAG_NAME -replace '-[A-Za-z0-9]+', ".$env:APPVEYOR_BUILD_NUMBER";
    }
    else {
        $env:packageVersion = $env:APPVEYOR_BUILD_VERSION -replace '\.[0-9]+$', '';
        $env:dllVersion = $env:APPVEYOR_BUILD_VERSION -replace '-[A-Za-z]+', '.';
    }
install:
- ps: >- 
    if ($env:APPVEYOR_REPO_TAG -eq "true") { 
        cinst msbuild-sonarqube-runner;
        cinst dotcover-cli;
    }
before_build:
- ps: >-
    nuget restore;
    ./set-versions.ps1 $env:packageVersion $env:dllVersion;
    if ($env:APPVEYOR_REPO_TAG -eq "true") { 
        ./sonar.ps1 begin $env:sonarLogin $env:APPVEYOR_REPO_TAG_NAME 
    }
test_script:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true") { 
        dotCover analyze dotCover.xml -TargetExecutable="$($(Get-Command nunit-console).Source)";
        ./sonar.ps1 end $env:sonarLogin;
    } else {
        nunit-console ./nunit.migrator.tests/bin/Release/net452/nunit.migrator.tests.dll /xml TestResult.xml
        $wc = New-Object 'System.Net.WebClient';
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))
    }
artifacts:
  - path: 'nunit.migrator.vsix\**\*.vsix'
    name: vsix
  - path: 'nunit.migrator\**\*.nupkg'
    name: nuget
deploy:
- provider: NuGet
  api_key: $(nugetOrgApiKey)
  skip_symbols: true
  artifact: nuget
  on:
    appveyor_repo_tag: true
- provider: GitHub
  auth_token:
    secure: PfDIBcJmuoBtInoTSoSMOQCUtlk0+WU6wRYG9/MwWbFAEhOLJnQ1vhMu3FcOXLHt
  artifact: 'nuget, vsix'
  prerelease: $(isPrerelease)
  on:
    appveyor_repo_tag: true