version: 0.1.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test:
  assemblies:
    only:
      - '**\*.Tests.dll'